# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a3e3cb7c-cfca-4471-8e6f-0a047cf477ff";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a3e3cb7c-cfca-4471-8e6f-0a047cf477ff".device = "/dev/disk/by-uuid/a3e3cb7c-cfca-4471-8e6f-0a047cf477ff";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/214E-5359";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-01b4b8c5-f250-4434-b00a-86d91e74ce05"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
